/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssinarRssRouteImport } from './routes/assinar-rss'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DesenvolvimentoRouteImport } from './routes/desenvolvimento'
import { Route as PericiaContabilRouteImport } from './routes/pericia-contabil'
import { Route as PericiaDigitalRouteImport } from './routes/pericia-digital'
import { Route as PericiaDocumentalRouteImport } from './routes/pericia-documental'
import { Route as PericiaGrafotecnicaRouteImport } from './routes/pericia-grafotecnica'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRssRoute = AssinarRssRouteImport.update({
  id: '/assinar-rss',
  path: '/assinar-rss',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DesenvolvimentoRoute = DesenvolvimentoRouteImport.update({
  id: '/desenvolvimento',
  path: '/desenvolvimento',
  getParentRoute: () => rootRouteImport,
} as any)
const PericiaContabilRoute = PericiaContabilRouteImport.update({
  id: '/pericia-contabil',
  path: '/pericia-contabil',
  getParentRoute: () => rootRouteImport,
} as any)
const PericiaDigitalRoute = PericiaDigitalRouteImport.update({
  id: '/pericia-digital',
  path: '/pericia-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const PericiaDocumentalRoute = PericiaDocumentalRouteImport.update({
  id: '/pericia-documental',
  path: '/pericia-documental',
  getParentRoute: () => rootRouteImport,
} as any)
const PericiaGrafotecnicaRoute = PericiaGrafotecnicaRouteImport.update({
  id: '/pericia-grafotecnica',
  path: '/pericia-grafotecnica',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinar-rss': typeof AssinarRssRoute
  '/auditoria': typeof AuditoriaRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/pericia-contabil': typeof PericiaContabilRoute
  '/pericia-digital': typeof PericiaDigitalRoute
  '/pericia-documental': typeof PericiaDocumentalRoute
  '/pericia-grafotecnica': typeof PericiaGrafotecnicaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinar-rss': typeof AssinarRssRoute
  '/auditoria': typeof AuditoriaRoute
  '/contato': typeof ContatoRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/pericia-contabil': typeof PericiaContabilRoute
  '/pericia-digital': typeof PericiaDigitalRoute
  '/pericia-documental': typeof PericiaDocumentalRoute
  '/pericia-grafotecnica': typeof PericiaGrafotecnicaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinar-rss': typeof AssinarRssRoute
  '/auditoria': typeof AuditoriaRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/pericia-contabil': typeof PericiaContabilRoute
  '/pericia-digital': typeof PericiaDigitalRoute
  '/pericia-documental': typeof PericiaDocumentalRoute
  '/pericia-grafotecnica': typeof PericiaGrafotecnicaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinar-rss'
    | '/auditoria'
    | '/blog'
    | '/contato'
    | '/desenvolvimento'
    | '/pericia-contabil'
    | '/pericia-digital'
    | '/pericia-documental'
    | '/pericia-grafotecnica'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinar-rss'
    | '/auditoria'
    | '/contato'
    | '/desenvolvimento'
    | '/pericia-contabil'
    | '/pericia-digital'
    | '/pericia-documental'
    | '/pericia-grafotecnica'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/assinar-rss'
    | '/auditoria'
    | '/blog'
    | '/contato'
    | '/desenvolvimento'
    | '/pericia-contabil'
    | '/pericia-digital'
    | '/pericia-documental'
    | '/pericia-grafotecnica'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinarRssRoute: typeof AssinarRssRoute
  AuditoriaRoute: typeof AuditoriaRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  DesenvolvimentoRoute: typeof DesenvolvimentoRoute
  PericiaContabilRoute: typeof PericiaContabilRoute
  PericiaDigitalRoute: typeof PericiaDigitalRoute
  PericiaDocumentalRoute: typeof PericiaDocumentalRoute
  PericiaGrafotecnicaRoute: typeof PericiaGrafotecnicaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar-rss': {
      id: '/assinar-rss'
      path: '/assinar-rss'
      fullPath: '/assinar-rss'
      preLoaderRoute: typeof AssinarRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desenvolvimento': {
      id: '/desenvolvimento'
      path: '/desenvolvimento'
      fullPath: '/desenvolvimento'
      preLoaderRoute: typeof DesenvolvimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pericia-contabil': {
      id: '/pericia-contabil'
      path: '/pericia-contabil'
      fullPath: '/pericia-contabil'
      preLoaderRoute: typeof PericiaContabilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pericia-digital': {
      id: '/pericia-digital'
      path: '/pericia-digital'
      fullPath: '/pericia-digital'
      preLoaderRoute: typeof PericiaDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pericia-documental': {
      id: '/pericia-documental'
      path: '/pericia-documental'
      fullPath: '/pericia-documental'
      preLoaderRoute: typeof PericiaDocumentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pericia-grafotecnica': {
      id: '/pericia-grafotecnica'
      path: '/pericia-grafotecnica'
      fullPath: '/pericia-grafotecnica'
      preLoaderRoute: typeof PericiaGrafotecnicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinarRssRoute: AssinarRssRoute,
  AuditoriaRoute: AuditoriaRoute,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  DesenvolvimentoRoute: DesenvolvimentoRoute,
  PericiaContabilRoute: PericiaContabilRoute,
  PericiaDigitalRoute: PericiaDigitalRoute,
  PericiaDocumentalRoute: PericiaDocumentalRoute,
  PericiaGrafotecnicaRoute: PericiaGrafotecnicaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
