/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as DesenvolvimentoRouteImport } from './routes/desenvolvimento'
import { Route as PericiaContabilRouteImport } from './routes/pericia-contabil'
import { Route as PericiaDigitalRouteImport } from './routes/pericia-digital'
import { Route as PericiaDocumentalRouteImport } from './routes/pericia-documental'
import { Route as PericiaGrafotecnicaRouteImport } from './routes/pericia-grafotecnica'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const DesenvolvimentoRoute = DesenvolvimentoRouteImport.update({
  id: '/desenvolvimento',
  path: '/desenvolvimento',
  getParentRoute: () => rootRouteImport,
} as any)
const PericiaContabilRoute = PericiaContabilRouteImport.update({
  id: '/pericia-contabil',
  path: '/pericia-contabil',
  getParentRoute: () => rootRouteImport,
} as any)
const PericiaDigitalRoute = PericiaDigitalRouteImport.update({
  id: '/pericia-digital',
  path: '/pericia-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const PericiaDocumentalRoute = PericiaDocumentalRouteImport.update({
  id: '/pericia-documental',
  path: '/pericia-documental',
  getParentRoute: () => rootRouteImport,
} as any)
const PericiaGrafotecnicaRoute = PericiaGrafotecnicaRouteImport.update({
  id: '/pericia-grafotecnica',
  path: '/pericia-grafotecnica',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/pericia-contabil': typeof PericiaContabilRoute
  '/pericia-digital': typeof PericiaDigitalRoute
  '/pericia-documental': typeof PericiaDocumentalRoute
  '/pericia-grafotecnica': typeof PericiaGrafotecnicaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/pericia-contabil': typeof PericiaContabilRoute
  '/pericia-digital': typeof PericiaDigitalRoute
  '/pericia-documental': typeof PericiaDocumentalRoute
  '/pericia-grafotecnica': typeof PericiaGrafotecnicaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/pericia-contabil': typeof PericiaContabilRoute
  '/pericia-digital': typeof PericiaDigitalRoute
  '/pericia-documental': typeof PericiaDocumentalRoute
  '/pericia-grafotecnica': typeof PericiaGrafotecnicaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/desenvolvimento'
    | '/pericia-contabil'
    | '/pericia-digital'
    | '/pericia-documental'
    | '/pericia-grafotecnica'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/desenvolvimento'
    | '/pericia-contabil'
    | '/pericia-digital'
    | '/pericia-documental'
    | '/pericia-grafotecnica'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/desenvolvimento'
    | '/pericia-contabil'
    | '/pericia-digital'
    | '/pericia-documental'
    | '/pericia-grafotecnica'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  DesenvolvimentoRoute: typeof DesenvolvimentoRoute
  PericiaContabilRoute: typeof PericiaContabilRoute
  PericiaDigitalRoute: typeof PericiaDigitalRoute
  PericiaDocumentalRoute: typeof PericiaDocumentalRoute
  PericiaGrafotecnicaRoute: typeof PericiaGrafotecnicaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desenvolvimento': {
      id: '/desenvolvimento'
      path: '/desenvolvimento'
      fullPath: '/desenvolvimento'
      preLoaderRoute: typeof DesenvolvimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pericia-contabil': {
      id: '/pericia-contabil'
      path: '/pericia-contabil'
      fullPath: '/pericia-contabil'
      preLoaderRoute: typeof PericiaContabilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pericia-digital': {
      id: '/pericia-digital'
      path: '/pericia-digital'
      fullPath: '/pericia-digital'
      preLoaderRoute: typeof PericiaDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pericia-documental': {
      id: '/pericia-documental'
      path: '/pericia-documental'
      fullPath: '/pericia-documental'
      preLoaderRoute: typeof PericiaDocumentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pericia-grafotecnica': {
      id: '/pericia-grafotecnica'
      path: '/pericia-grafotecnica'
      fullPath: '/pericia-grafotecnica'
      preLoaderRoute: typeof PericiaGrafotecnicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  DesenvolvimentoRoute: DesenvolvimentoRoute,
  PericiaContabilRoute: PericiaContabilRoute,
  PericiaDigitalRoute: PericiaDigitalRoute,
  PericiaDocumentalRoute: PericiaDocumentalRoute,
  PericiaGrafotecnicaRoute: PericiaGrafotecnicaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
